spring:
  application:
    name: social_server
  datasource:
    url: "jdbc:h2:mem:yanawa;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
