server:
  port: 14122

logging:
    level:
        our:
            fashionablesimba.yanawa: debug

spring:
  application:
      name: matching_service
  messages:
     basename: i18n/messages
     encoding: UTF-8
     cache-duration: PT1H
  h2:
     console:
       enabled: true
       path: /h2-console
  datasource:
     url: jdbc:mysql://yanawadb.co0a79gthsyg.ap-northeast-2.rds.amazonaws.com:3306/yanawadb
     driver-class-name: com.mysql.cj.jdbc.Driver
     username: admin
     password: yanawaadmin
     hikari:
       minimum-idle: 1
       maximum-pool-size: 5
       pool-name: H2_DB
  jpa:
    hibernate:
      ddl-auto: create

